server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317

ingester:
  lifecycler:
    ring:
      kvstore:
        store: "inmemory"

compactor:
  compaction:
    block_retention: "24h"

querier: {}

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/chunks